# Generated by Django 3.1.8 on 2021-05-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20210504_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='identity',
            new_name='hero_name',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='name',
            new_name='secret_identity',
        ),
    ]
